### PR TITLE
Mimicking the "AlphaZero" paper

### PR DESCRIPTION
**Pull request by benediamond**
This commit adds a number of overhauls, all with an eye towards the latest AlphaZero [paper](https://arxiv.org/pdf/1712.01815.pdf) by Silver, Hassabis et. al. Roughly, these are:
- I've changed the chess position feature representation to the input stack described in "Mastering Chess...". Notably, in the previous version, the board failed to oriented to the perspective of the current player, an intervention which seems crucial. The history depth (AlphaZero uses T = 8) is also easily modifiable, for testing purposes.
- The output "action space" has also been changed to match the description in "Mastering Chess". In particular, we use an 8x8x73 stack, where depth of the stack indicates the relative position of the target square to the source square.
- Following "Mastering Chess", the evaluation step has been eliminated, and newly generated models automatically supplant existing ones. The "evaluate.py" file has been preserved; now, on the other hand, it simply provides the (helpful for testing) functionality of comparing the present model against prior ones.
- I've hashed the move generation process, leading to speedups in self-play and evaluation.
- The distributed training functionality has been temporarily disabled. I will reenable this according to the new paradigm if results look good.

### CODE REVIEW

**Comment by Zeta36** [comment]
Very good work!!

**Comment by Zeta36** [comment]
I've detected a bug in optimize.py line 166.

`state = env.gather_features(self.config.model.t_history)`

gather_features() always return a state with all t_history planes to zero except the current board state. I think just with a fen board you cannot reconstruct the 8 former steps in order to form the planes like DeepMind did.

You can do it in player_chess.py in line 183 but that's because you have all previous steps game follows, but in the optimize you just read a fean board from the saved play data files and that's not enough I think to fill the 8 previous step planes.

You could try doing in optimize.py something like this:

```
        state_list = []
        policy_list = []
        z_list = []
        aux_move_number = 1
        movements = []
        for state, policy, z in data:
            move_number = int((ChessEnv().update(state, movements)).board.fen().split(" ")[5])
            if aux_move_number < move_number:
                if len(movements) > 8:
                    movements.pop(0)
                movements.append(env.observation)
                aux_move_number = move_number
            else:
                aux_move_number = 1
                movements = []

            env = ChessEnv().update(state, movements)  #or something similar to feed the former movements
            .....
            .....
```

**Comment by benediamond** [comment]
Samuel, great catch, thank you. I'll look into working out this fix as soon as I can.

**Comment by Zeta36** [comment]
Benjamin I think that the function gather_features() is not working well neither in "player_chess.py". I've follow the trace of a MCTS and you never fill more than 2 planes in the history even if there are 5 o more movements. I sent you an email about this.

**Comment by Zeta36** [comment]
Also, Benjamin. You did not re-normalize the legal moves as DeepMind does in the paper. The easiest way is in player_chess.py add this into select_action_q_and_u(): 

        # re-normalize in legal moves
        p_ = p_ * legal_moves

        if np.sum(p_) > 0:
            p_ = p_ / np.sum(p_)

**Comment by Zeta36** [comment]
Finally, DeepMind says they finish any game of self-play lasting more than the mean chess number of movements. I.e.; if after X movements (paper does not say which) the game is still not over, they finish it and assign a "draw" to the result. I think this is easy to implement.

**Comment by benediamond** [comment]
Samuel, I indeed perform the normalization during the `expand_and_evaluate` process (that way we do it just once). see the code:
```python
        leaf_p = leaf_p * legal_labels  # mask policy vector and renormalize.
        leaf_p = leaf_p / sum(leaf_p) if sum(leaf_p) > 0 else leaf_p
```
(I've just now added the divide-by-zero check as you suggested, this will be implemented in the next commit.)

I'm a little bit wary of assigning draws, because the fewer draws the better as far as getting strong training signals. But you're right that it would be easy; I will think about this.

As for the issues with `gather_features`, I am addressing those now.

**Comment by Zeta36** [comment]
Good job, @benediamond. I really think you are doing a great job and that you will finally get it if you continue in this way.

**Comment by benediamond** [comment]
@Zeta36 Thank you!

And yes, the problem is that in `self_play.py` line 59, we pass only the FEN to the `ChessPlayer`:
```python
            action = ai.action(self.env.fen)
```
I will fix this as well as in the `convert_to_training_data` case.

**Pull request merged**
