### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by benediamond**
A tiny fix in the evaluator, in light of the previous changes.

### CODE REVIEW

**Comment by Zeta36** [comment]
@benediamond, I've been doing a trace of your code and I'm afraid 'player_chess.py' is still failing in the sense that the history of movements for the planes (gathering) is mixed between the nodes of the MTCS search. If you follow the trace you will see how the environments history state is not consistent and in some way it's mixed.

Stop and debug in line 182 to see this after some movements:

`state = env.gather_features(self.config.model.t_history)`

In 'optimize.py' it seems that it work but I'm not sure if you are inserting the current state board in the correct way. I think you insert current board state in the last plane in 'player_chess.py' but in 'optimize.py' I think you insert it in the first plane before inserting the history ones.

You can debug this in line 177:

`state = np.concatenate((features[:7], np.concatenate(history)))`

**Comment by benediamond** [comment]
@Zeta36, Thanks for investigating this. I thought that in `chessenv.py`, line 150, `copy.copy` was sufficient. But is it possible that it must be replaced by `copy.deepcopy`? Could you give this a try? I will also take a look.

**Comment by benediamond** [comment]
Here is another thought. I've found that `player_chess.py` consumes large amounts of memory over time, and eventually leads to memory overflows. I think the problem is that _every_ key remains stored in `self.var_n`, `self.var_q`, etc., even when moves are made. In AlphaGo Zero, the unused branches of the tree are discarded after a move is made. Perhaps we must do something like this: after an irreversible move (capture, pawn push, etc.) discard the entries corresponding to keys which are irrelevant. What do you think?

**Comment by benediamond** [comment]
I agree that `convert_to_training_data` has problems, but because the _repetitions_ planes will always be empty :( I will think about this.

But I've checked line 182 `state = env.gather_features(self.config.model.t_history)` in `player_chess.py`, and I am not seeing any issues. Maybe you could elaborate on this "mixing" you saw?

**Comment by benediamond** [comment]
I see the issue with `convert_to_training_data`. The problem is that in `self_play.py`, `save_play_data` line 67:
```python
        data = self.white.moves + self.black.moves
```
the games of the entire move are concatenated, as _white moves_ then _black moves_. Thus they aren't in sequence when they're saved into the file. They should be interleaved. I will work on this.

**Pull request merged**
