### PR TITLE
More concurrency

### PR DESCRIPTION
**Pull request by benediamond**
Implemented some fantastic concurrency improvements, due to @Akababa. Self-play games are now ~2-10 times faster.

I believe the below snippets provide a solution to the problem I mentioned in https://github.com/Akababa/Chess-Zero/commit/4de90df0e1c1b832d4f5ee591a879b2988462ce9#commitcomment-26427633.

https://github.com/benediamond/chess-alpha-zero/blob/8368046ba87f592f9e9110a4e56b95a16b52c63f/src/chess_zero/worker/self_play.py#L38-L63

https://github.com/benediamond/chess-alpha-zero/blob/8368046ba87f592f9e9110a4e56b95a16b52c63f/src/chess_zero/worker/self_play.py#L88-L94

I'm now working out one last crash that happens when play data is written and the model is refreshed. Stay tuned.

### CODE REVIEW

**Comment by Akababa** [comment]
Nice! I think the threadpool is extraneous as you can just run consume_buffer (basically as_completed) on the main thread. I think this would be cleaner:
edit: actually this blocks while waiting for results, I'll fix it later

```python
def as_completed(futures):
 while True:
  for f in futures:
   if f.done():
    futures.remove(f)
    yield f.result()
  time.sleep(0.01)
```

**Comment by benediamond** [comment]
But wouldn't this essentially do the same thing it was originally doing...? The key is that the futures should be popped and the results returned asynchronously. Right?

**Comment by Akababa** [comment]
I updated my as_completed, let me know if it's sensible! Since it's a generator it should only block on 
```python
for result in as_completed(futures)
```

**Comment by benediamond** [comment]
Awesome, looks great! This is certainly simpler.

I'm still having some sort of crash when the model is loaded. I think it may have to do with calling `predict_on_batch` in `api_chess.py` while the model is being replaced / overwritten. I'll keep working and keep this thread posted.

**Comment by benediamond** [comment]
Using this new setup, I'm once again getting behavior where the games are dumped in "batches" instead of asynchronously. Here's the code:

https://github.com/benediamond/chess-alpha-zero/blob/5dc8b6306e16ea0e0aa04e48d2c33f223f2b0613/src/chess_zero/worker/self_play.py#L38-L63

any thoughts?

**Comment by Akababa** [comment]
Oh, haha I just saw this. Great to know it worked!

**Pull request closed without merging**
